image: node:14
cache:
  paths:
    - node_modules/
stages:
  - test
  - package
  - deploy

variables:
  NODE_ENV: production
  ENV: production
  LC_ALL: C.UTF-8

before_script:
  - NODE_ENV=debug npm install
  - cp config.example.json config.json

test:
  stage: test
  dependencies: []
  interruptible: true
  script:
    - npm test

webext:
  stage: package
  dependencies: []
  interruptible: true
  script:
    - npm run package:webext
    - mv web-ext-artifacts/renewedtab.zip renewedtab.zip
  artifacts:
    expire_in: 1 week
    paths:
      - renewedtab.zip

pages:
  stage: deploy
  dependencies: []
  interruptible: true
  script:
    - npm run build:app
    - cp -r dist/webext/app public
  artifacts:
    paths:
      - public
  only:
    - master

# firefox:
#   stage: deploy
#   dependencies: ["webext"]
#   interruptible: false
#   script:
#     - VERSION=${CI_COMMIT_REF_NAME:1}
#     - JWT=$(node utils/make_jwt.js $FIREFOX_JWT_ISSUER $FIREFOX_JWT_SECRET)
#     - >
#       curl "https://addons.mozilla.org/api/v4/addons/${FIREFOX_EXTENSION_ID}/versions/${VERSION}/" \
#         -g -XPUT --form "upload=@renewedtab.zip" -H "Authorization: JWT ${JWT}"
#   only:
#     - tags
