image: node:14
cache:
  paths:
    - node_modules/
stages:
  - test
  - deploy

variables:
  ENV: production
  LC_ALL: C.UTF-8

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  interruptible: true
  script:
    - "echo '{ \"PROXY_URL\": \"https://rubenwardy.com/homescreen/proxy/\" }' > config.json"
    - npm run build
    - cp -r dist/app public
  artifacts:
    paths:
      - public
  only:
    - master
