image: node:14
cache:
  paths:
    - node_modules/
stages:
  - test
  - deploy

variables:
  NODE_ENV: production
  ENV: production
  LC_ALL: C.UTF-8

before_script:
  - npm install
  - cp config_client.example.json config_client.json
  - cp config_server.example.json config_server.json

test:
  stage: test
  dependencies: []
  interruptible: true
  script:
    - npm test

firefox:
  stage: deploy
  dependencies: []
  interruptible: true
  script:
    - npm run package:firefox
    - mv web-ext-artifacts/homescreen.zip firefox-homescreen.zip
  artifacts:
    expire_in: 1 week
    paths:
      - firefox-homescreen.zip
  only:
    - master

pages:
  stage: deploy
  dependencies: []
  interruptible: true
  script:
    - npm run build:app
    - cp -r dist/webext/app public
  artifacts:
    paths:
      - public
  only:
    - master
