image: node:14

variables:
  ENV: production
  LC_ALL: C.UTF-8

before_script:
  - npm install

pages:
  stage: deploy
  interruptible: true
  script:
    - "echo '{ \"PROXY_URL\": \"https://rubenwardy.com/homescreen/proxy/\" }' > config.json"
    - npm run build
    - cp -r dist/app public
  artifacts:
    paths:
      - public
  only:
    - master
