image: node:14
cache:
  paths:
    - node_modules/
stages:
  - test
  - deploy

variables:
  NODE_ENV: production
  ENV: production
  LC_ALL: C.UTF-8

before_script:
  - NODE_ENV=debug npm install
  - cp config.example.json config.json

test:
  stage: test
  dependencies: []
  interruptible: true
  script:
    - npm test

webext:
  stage: deploy
  dependencies: []
  interruptible: true
  script:
    - npm run package:webext
    - mv web-ext-artifacts/homescreen.zip homescreen.zip
  artifacts:
    expire_in: 1 week
    paths:
      - homescreen.zip
  only:
    - master

pages:
  stage: deploy
  dependencies: []
  interruptible: true
  script:
    - npm run build:app
    - cp -r dist/webext/app public
  artifacts:
    paths:
      - public
  only:
    - master
