name: CI/CD

on:
  push:
    branches:
      - main  # 替换为您的主分支名称
    tags:
      - '*'  # 所有标签都触发

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run unit tests
        run: |
          npm run trans:check
          npm test
          npm run lint

  ui-chrome:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run UI tests on Chrome
        env:
          SENTRY_DSN: ""
          TARGET: chrome
        run: |
          npm run build:app
          npm run uitest:chrome

  ui-firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run UI tests on Firefox
        env:
          SENTRY_DSN: ""
          TARGET: firefox
        run: |
          npm run build:app
          npm run uitest:firefox

  webext:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Package Web Extension
        run: |
          npm run package:webext
          mv web-ext-artifacts/*.zip .
          mv dist/webext/app/*.js.map .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webext-artifacts
          path: |
            chrome.zip
            firefox.zip
            edge.zip
            "*.js.map"

  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Deploy to Pages
        env:
          NODE_ENV: production
        run: |
          npm run build:app
          cp -r dist/webext/app public

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: public

  sentry:
    runs-on: ubuntu-latest
    needs: webext

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Prepare artifacts for Sentry
        run: |
          mkdir -p dist
          mv chrome.zip dist/chrome.zip
          pushd dist && unzip chrome.zip && popd
          mv *.js.map dist/app/

      - name: Install Sentry CLI
        run: npm install @sentry/cli

      - name: Deploy to Sentry
        env:
          VERSION: "renewedtab@$GITHUB_REF"
          SENTRY_ORG: "renewedtab"
          SENTRY_PROJECT: "renewedtab"
        run: |
          sentry-cli releases new $VERSION
          sentry-cli releases set-commits --auto $VERSION
          sentry-cli releases deploys $VERSION new -e production
          sentry-cli releases files $VERSION upload-sourcemaps --validate --ext ts --ext js --ext tsx --ext map dist
          sentry-cli releases finalize $VERSION

      - name: Cleanup artifacts
        run: rm -rf dist

  chrome:
    runs-on: ubuntu-latest
    needs: webext

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Upload Chrome extension to server
        run: npm run upload:chrome chrome.zip

  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - test
      - ui-chrome
      - ui-firefox
      - webext
      - pages
      - sentry
      - chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build Docker image
        run: |
          docker build -t dockerzvip/renewedtab:$GITHUB_SHA .
          docker tag dockerzvip/renewedtab:$GITHUB_SHA dockerzvip/renewedtab:latest

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push dockerzvip/renewedtab:$GITHUB_SHA
          docker push dockerzvip/renewedtab:latest
