name: CI/CD

on:
  push:
    branches:
      - main  # 替换为您的主分支名称
    tags:
      - '*'  # 所有标签都触发

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run unit tests
        run: |
          npm run trans:check
          npm test
          npm run lint

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build Docker image
        run: |
          docker build -t dockerzvip/renewedtab:$GITHUB_SHA .
          docker tag dockerzvip/renewedtab:$GITHUB_SHA dockerzvip/renewedtab:latest

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push dockerzvip/renewedtab:$GITHUB_SHA
          docker push dockerzvip/renewedtab:latest
